language: python
install:
  - pip freeze | xargs pip uninstall -y
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - flake8 .
script:
  - coverage run --source=./ -m py.test
after_success:
  - coveralls
