on: [pull_request]
name: "Set status on pull_request"

jobs:
  wip:
    name: "Set status"
    runs-on: ubuntu-latest
    steps:
    - uses: wip/action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
